//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityWeb.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhSachLop
    {
        public string maLop { get; set; }
        public string maSinhVien { get; set; }
        public string tenLop { get; set; }
    
        public virtual LopMonHoc LopMonHoc { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
