//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityWeb.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuanTri
    {
        public string maQuanTri { get; set; }
        public string tenQuanTri { get; set; }
        public string queQuan { get; set; }
        public Nullable<System.DateTime> ngaySinh { get; set; }
        public string tenDangNhap { get; set; }
        public string maBaiViet { get; set; }
    
        public virtual BaiViet BaiViet { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
