//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityWeb.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SinhVien()
        {
            this.BangDiems = new HashSet<BangDiem>();
            this.DanhSachLops = new HashSet<DanhSachLop>();
        }
    
        public string maSinhVien { get; set; }
        public string tenSinhVien { get; set; }
        public string queQuan { get; set; }
        public Nullable<System.DateTime> ngaySinh { get; set; }
        public Nullable<int> namNhapHoc { get; set; }
        public string maNganh { get; set; }
        public string eMail { get; set; }
        public string tenDangNhap { get; set; }
        public Nullable<int> gioiTinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BangDiem> BangDiems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhSachLop> DanhSachLops { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
